version: "3.8"

services:
  frontend:
    build:
      context: ./rewards-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - db

  backend:
    build:
      context: ./rewards-backend
      dockerfile: Dockerfile
    env_file: ./rewards-backend/.env
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB=$DB_NAME
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@db:$DB_PORT/$DB_NAME
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "$DB_PORT:$DB_PORT"
    env_file: ./rewards-backend/.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

